--- #YAML:1.0
name:               DBD-PgPP
version:            0.06
abstract:           ~
author:
    - OYAMA Hiroyuki <oyama@module.jp>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:         1.59
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
